"""Cross-Crypto Protocol v3 — implementación Python."""

__version__ = "3.0.0"

from .errors import CrossCryptoError, CrossCryptoErrorCode
from .ccenc import (
    decrypt_ccenc_bytes,
    decrypt_file,
    encrypt_ccenc_bytes,
    encrypt_file,
    read_ccenc_header,
    read_ccenc_file_header,
)
from .json_api import (
    decrypt_json,
    decrypt_text,
    encrypt_json,
    encrypt_text,
    sign_json,
    sign_text,
    verify_json,
    verify_text,
)
from .jwe import decrypt_bytes, encrypt_bytes, read_jwe_protected_header
from .jws import (
    is_valid_signature,
    read_jws_protected_header,
    sign_bytes,
    verify_bytes,
)
from .keys import (
    generate_ed25519_key_pair,
    generate_rsa_key_pair,
    key_id_from_public_key,
)
from .types import (
    JWE_ALG,
    JWE_ENC,
    JWE_TYP,
    JWS_ALG,
    JWS_TYP,
    PROTOCOL_VERSION,
    CcencDecryptResult,
    CcencHeader,
    DecryptResult,
    JweEnvelope,
    JweProtectedHeader,
    JwsEnvelope,
    JwsProtectedHeader,
    KeyPair,
    RsaKeyPair,
    Ed25519KeyPair,
    VerifyResult,
)

__all__ = [
    "__version__",
    "CrossCryptoError",
    "CrossCryptoErrorCode",
    "PROTOCOL_VERSION",
    "JWE_ALG",
    "JWE_ENC",
    "JWE_TYP",
    "JWS_ALG",
    "JWS_TYP",
    "JweEnvelope",
    "JweProtectedHeader",
    "JwsEnvelope",
    "JwsProtectedHeader",
    "KeyPair",
    "RsaKeyPair",
    "Ed25519KeyPair",
    "DecryptResult",
    "VerifyResult",
    "CcencDecryptResult",
    "CcencHeader",
    "generate_rsa_key_pair",
    "generate_ed25519_key_pair",
    "key_id_from_public_key",
    "encrypt_ccenc_bytes",
    "decrypt_ccenc_bytes",
    "encrypt_file",
    "decrypt_file",
    "read_ccenc_header",
    "read_ccenc_file_header",
    "encrypt_bytes",
    "decrypt_bytes",
    "read_jwe_protected_header",
    "sign_bytes",
    "verify_bytes",
    "is_valid_signature",
    "read_jws_protected_header",
    "encrypt_json",
    "decrypt_json",
    "encrypt_text",
    "decrypt_text",
    "sign_json",
    "verify_json",
    "sign_text",
    "verify_text",
]
