name: Publicar Paquete a PyPI

on:
  release:
    types: [published]

jobs:
  build-y-publicar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # o '3.12', '3.11', etc.

    - name: Instalar dependencias de construcción
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools twine

    - name: Construir paquete
      run: python setup.py sdist bdist_wheel

    - name: Publicar paquete a PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}